// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  utagInfo: {
      whyIrresistibles: {
          page_category: 'home | irresistibles',  
          page_name: 'home',
          page_section: 'home',
          page_subCategory: 'home',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
      products: {
          page_category: 'products | irresistibles',  
          page_name: 'products',
          page_section: 'products',
          page_subCategory: 'products',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
      product: [
          {
              page_category: 'products | irresistibles',  
              page_name: 'Daily Plus',
              page_section: 'Daily Plus',
              page_subCategory: 'product',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'products | irresistibles',  
              page_name: 'Cal Mag D',
              page_section: 'Cal Mag D',
              page_subCategory: 'product',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'products | irresistibles',  
              page_name: 'Proteína Vegetal',
              page_section: 'Proteína Vegetal',
              page_subCategory: 'product',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          }, 
          {
            page_category: 'products | irresistibles',  
            page_name: 'Omega 3 Plus',
            page_section: 'Omega 3 Plus',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'C Plus',
            page_section: 'C Plus',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'B Plus / B Complex Dual Release',
            page_section: 'B Plus / B Complex Dual Release',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'HSN',
            page_section: 'HSN',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'Agua Micelar',
            page_section: 'Agua Micelar',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'Pasta de Dientes',
            page_section: 'Pasta de Dientes',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }, 
        {
            page_category: 'products | irresistibles',  
            page_name: 'L.O.C. Limpiador Multiusos',
            page_section: 'L.O.C. Limpiador Multiusos',
            page_subCategory: 'product',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }
      ],
      ingredients: [ 
        {
            page_category: 'ingredients | irresistibles',  
            page_name: 'ingredients',
            page_section: 'ingredients',
            page_subCategory: 'Productos Naturales y Belleza',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'products | irresistibles',  
            page_name: 'ingredients',
            page_section: 'ingredients',
            page_subCategory: 'Productos para el Cuidado Personal y Amway Home',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },  
      ],
      solutions: {
          page_category: 'solutions | irresistibles',  
          page_name: 'solutions',
          page_section: 'solutions',
          page_subCategory: 'El camino IRRESISTIBLE',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
      solution: [
          {
              page_category: 'solutions | irresistibles',  
              page_name: 'MOVIMIENTO CONSTANTE',
              page_section: 'MOVIMIENTO CONSTANTE',
              page_subCategory: 'solutions',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'solutions | irresistibles',  
              page_name: 'DESAFÍA TUS IDEAS',
              page_section: 'DESAFÍA TUS IDEAS',
              page_subCategory: 'solutions',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'solutions | irresistibles',  
              page_name: 'SONRISA IDEAL',
              page_section: 'SONRISA IDEAL',
              page_subCategory: 'solutions',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
            page_category: 'solutions | irresistibles',  
            page_name: 'BELLEZA INTEGRAL',
            page_section: 'BELLEZA INTEGRAL',
            page_subCategory: 'solutions',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'solutions | irresistibles',  
            page_name: 'ACTIVIDAD DIARIA',
            page_section: 'ACTIVIDAD DIARIA',
            page_subCategory: 'solutions',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'solutions | irresistibles',  
            page_name: 'EN LA MIRA',
            page_section: 'EN LA MIRA',
            page_subCategory: 'solutions',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'solutions | irresistibles',  
            page_name: 'ECO ACTIVO',
            page_section: 'ECO ACTIVO',
            page_subCategory: 'solutions',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        }
      ],
      tools: {
          page_category: 'tools | irresistibles',  
          page_name: 'tools',
          page_section: 'tools',
          page_subCategory: 'Conoce las Herramientas IRRESISTIBLES',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
      country: [
          {
              page_category: 'tools | irresistibles',  
              page_name: 'tools',
              page_section: 'tools',
              page_subCategory: 'Catálogo Irresistibles',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'tools | irresistibles',  
              page_name: 'tools',
              page_section: 'tools',
              page_subCategory: 'Looks Irresistibles',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
              page_category: 'tools | irresistibles',  
              page_name: 'tools',
              page_section: 'tools',
              page_subCategory: 'Perfiles Irresistibles',
              site_country: '',
              site_currencyCode: '',  
              site_language: 'es',  
              site_prefix: 'amway',
              site_region: 'americas', 
              site_subRegion: 'latam', 
              site_type: 'desktop',  
              site_type_short: 'web', 
              site_webProperty: 'ecommerce',  
              site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
          },
          {
            page_category: 'tools | irresistibles',  
            page_name: 'tools',
            page_section: 'tools',
            page_subCategory: 'Infografías Irresistibles',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'tools | irresistibles',  
            page_name: 'tools',
            page_section: 'tools',
            page_subCategory: 'Repositorio',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
        {
            page_category: 'tools | irresistibles',  
            page_name: 'tools',
            page_section: 'tools',
            page_subCategory: 'Entrenamientos Irresistibles',
            site_country: '',
            site_currencyCode: '',  
            site_language: 'es',  
            site_prefix: 'amway',
            site_region: 'americas', 
            site_subRegion: 'latam', 
            site_type: 'desktop',  
            site_type_short: 'web', 
            site_webProperty: 'ecommerce',  
            site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
        },
      ],
      buy: {
          page_category: 'buy | irresistible',  
          page_name: 'buy',
          page_section: 'buy',
          page_subCategory: 'COMPRAR',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
      sponsor: {
          page_category: 'sponsor | irresistible',  
          page_name: 'sponsor',
          page_section: 'sponsor',
          page_subCategory: 'sponsors',
          site_country: '',
          site_currencyCode: '',  
          site_language: 'es',  
          site_prefix: 'amway',
          site_region: 'americas', 
          site_subRegion: 'latam', 
          site_type: 'desktop',  
          site_type_short: 'web', 
          site_webProperty: 'ecommerce',  
          site_webProperty_mod: 'www.amway.com.mx | ecommerce', 
      },
  }
};
